changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - someuser
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"